/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PairRouteImport } from './routes/pair'
import { Route as NitromapRouteImport } from './routes/_nitromap'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as ChatDraftDraftIdRouteImport } from './routes/_chat.draft.$draftId'
import { Route as ChatEnvironmentIdThreadIdRouteImport } from './routes/_chat.$environmentId.$threadId'
import { Route as NitromapProjectsEnvironmentIdProjectIdWorkRouteImport } from './routes/_nitromap.projects.$environmentId.$projectId.work'
import { Route as NitromapProjectsEnvironmentIdProjectIdMapMaintenanceRouteImport } from './routes/_nitromap.projects.$environmentId.$projectId.map-maintenance'
import { Route as NitromapProjectsEnvironmentIdProjectIdMapRouteImport } from './routes/_nitromap.projects.$environmentId.$projectId.map'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const NitromapRoute = NitromapRouteImport.update({
  id: '/_nitromap',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatDraftDraftIdRoute = ChatDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatEnvironmentIdThreadIdRoute =
  ChatEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)
const NitromapProjectsEnvironmentIdProjectIdWorkRoute =
  NitromapProjectsEnvironmentIdProjectIdWorkRouteImport.update({
    id: '/projects/$environmentId/$projectId/work',
    path: '/projects/$environmentId/$projectId/work',
    getParentRoute: () => NitromapRoute,
  } as any)
const NitromapProjectsEnvironmentIdProjectIdMapMaintenanceRoute =
  NitromapProjectsEnvironmentIdProjectIdMapMaintenanceRouteImport.update({
    id: '/projects/$environmentId/$projectId/map-maintenance',
    path: '/projects/$environmentId/$projectId/map-maintenance',
    getParentRoute: () => NitromapRoute,
  } as any)
const NitromapProjectsEnvironmentIdProjectIdMapRoute =
  NitromapProjectsEnvironmentIdProjectIdMapRouteImport.update({
    id: '/projects/$environmentId/$projectId/map',
    path: '/projects/$environmentId/$projectId/map',
    getParentRoute: () => NitromapRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/projects/$environmentId/$projectId/map': typeof NitromapProjectsEnvironmentIdProjectIdMapRoute
  '/projects/$environmentId/$projectId/map-maintenance': typeof NitromapProjectsEnvironmentIdProjectIdMapMaintenanceRoute
  '/projects/$environmentId/$projectId/work': typeof NitromapProjectsEnvironmentIdProjectIdWorkRoute
}
export interface FileRoutesByTo {
  '/': typeof ChatIndexRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/projects/$environmentId/$projectId/map': typeof NitromapProjectsEnvironmentIdProjectIdMapRoute
  '/projects/$environmentId/$projectId/map-maintenance': typeof NitromapProjectsEnvironmentIdProjectIdMapMaintenanceRoute
  '/projects/$environmentId/$projectId/work': typeof NitromapProjectsEnvironmentIdProjectIdWorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/_nitromap': typeof NitromapRouteWithChildren
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/_chat/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/_nitromap/projects/$environmentId/$projectId/map': typeof NitromapProjectsEnvironmentIdProjectIdMapRoute
  '/_nitromap/projects/$environmentId/$projectId/map-maintenance': typeof NitromapProjectsEnvironmentIdProjectIdMapMaintenanceRoute
  '/_nitromap/projects/$environmentId/$projectId/work': typeof NitromapProjectsEnvironmentIdProjectIdWorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pair'
    | '/settings'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/general'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/projects/$environmentId/$projectId/map'
    | '/projects/$environmentId/$projectId/map-maintenance'
    | '/projects/$environmentId/$projectId/work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pair'
    | '/settings'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/general'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/projects/$environmentId/$projectId/map'
    | '/projects/$environmentId/$projectId/map-maintenance'
    | '/projects/$environmentId/$projectId/work'
  id:
    | '__root__'
    | '/_chat'
    | '/_nitromap'
    | '/pair'
    | '/settings'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/general'
    | '/_chat/'
    | '/_chat/$environmentId/$threadId'
    | '/_chat/draft/$draftId'
    | '/_nitromap/projects/$environmentId/$projectId/map'
    | '/_nitromap/projects/$environmentId/$projectId/map-maintenance'
    | '/_nitromap/projects/$environmentId/$projectId/work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  NitromapRoute: typeof NitromapRouteWithChildren
  PairRoute: typeof PairRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_nitromap': {
      id: '/_nitromap'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NitromapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/draft/$draftId': {
      id: '/_chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof ChatDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$environmentId/$threadId': {
      id: '/_chat/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/$environmentId/$threadId'
      preLoaderRoute: typeof ChatEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_nitromap/projects/$environmentId/$projectId/work': {
      id: '/_nitromap/projects/$environmentId/$projectId/work'
      path: '/projects/$environmentId/$projectId/work'
      fullPath: '/projects/$environmentId/$projectId/work'
      preLoaderRoute: typeof NitromapProjectsEnvironmentIdProjectIdWorkRouteImport
      parentRoute: typeof NitromapRoute
    }
    '/_nitromap/projects/$environmentId/$projectId/map-maintenance': {
      id: '/_nitromap/projects/$environmentId/$projectId/map-maintenance'
      path: '/projects/$environmentId/$projectId/map-maintenance'
      fullPath: '/projects/$environmentId/$projectId/map-maintenance'
      preLoaderRoute: typeof NitromapProjectsEnvironmentIdProjectIdMapMaintenanceRouteImport
      parentRoute: typeof NitromapRoute
    }
    '/_nitromap/projects/$environmentId/$projectId/map': {
      id: '/_nitromap/projects/$environmentId/$projectId/map'
      path: '/projects/$environmentId/$projectId/map'
      fullPath: '/projects/$environmentId/$projectId/map'
      preLoaderRoute: typeof NitromapProjectsEnvironmentIdProjectIdMapRouteImport
      parentRoute: typeof NitromapRoute
    }
  }
}

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatEnvironmentIdThreadIdRoute: typeof ChatEnvironmentIdThreadIdRoute
  ChatDraftDraftIdRoute: typeof ChatDraftDraftIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatEnvironmentIdThreadIdRoute: ChatEnvironmentIdThreadIdRoute,
  ChatDraftDraftIdRoute: ChatDraftDraftIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface NitromapRouteChildren {
  NitromapProjectsEnvironmentIdProjectIdMapRoute: typeof NitromapProjectsEnvironmentIdProjectIdMapRoute
  NitromapProjectsEnvironmentIdProjectIdMapMaintenanceRoute: typeof NitromapProjectsEnvironmentIdProjectIdMapMaintenanceRoute
  NitromapProjectsEnvironmentIdProjectIdWorkRoute: typeof NitromapProjectsEnvironmentIdProjectIdWorkRoute
}

const NitromapRouteChildren: NitromapRouteChildren = {
  NitromapProjectsEnvironmentIdProjectIdMapRoute:
    NitromapProjectsEnvironmentIdProjectIdMapRoute,
  NitromapProjectsEnvironmentIdProjectIdMapMaintenanceRoute:
    NitromapProjectsEnvironmentIdProjectIdMapMaintenanceRoute,
  NitromapProjectsEnvironmentIdProjectIdWorkRoute:
    NitromapProjectsEnvironmentIdProjectIdWorkRoute,
}

const NitromapRouteWithChildren = NitromapRoute._addFileChildren(
  NitromapRouteChildren,
)

interface SettingsRouteChildren {
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  NitromapRoute: NitromapRouteWithChildren,
  PairRoute: PairRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
